//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TareasCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tareas_crud
    {
        public int id { get; set; }
        public string tecnico { get; set; }
        public string descripcion { get; set; }
        public string prioridad { get; set; }
        public string estado { get; set; }
    }
}
